# Generated by Django 2.0.2 on 2019-02-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(default='media/images/knight.jpg', upload_to='media/images'),
        ),
    ]
