# Generated by Django 3.0.7 on 2020-06-15 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20190411_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spellbook',
            name='character',
        ),
        migrations.RemoveField(
            model_name='spellbook',
            name='spell',
        ),
        migrations.RemoveField(
            model_name='character',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='character',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dexterity',
        ),
        migrations.RemoveField(
            model_name='character',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='character',
            name='wisdom',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Spell',
        ),
        migrations.DeleteModel(
            name='SpellBook',
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
    ]
