# Generated by Django 2.0.2 on 2019-02-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_character_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image',
        ),
    ]
